const mongoose = require("mongoose");

const AlertSchema = mongoose.Schema(
  {
    url: {
      type: String,
      required: true,
    },
    wilaya: {
      type: String,
      enum: [
        "Adrar",
        "Chlef",
        "Laghouat",
        "Oum El Bouaghi",
        "Batna",
        "Bejaia",
        "Biskra",
        "Bechar",
        "Blida",
        "Bouira",
        "Tamanrasset",
        "Tebessa",
        "Tlemcen",
        "Tiaret",
        "Tizi Ouzou",
        "Algiers",
        "Djelfa",
        "Jijel",
        "Setif",
        "Saïda",
        "Skikda",
        "Sidi Bel Abbes",
        "Annaba",
        "Guelma",
        "Constantine",
        "Medea",
        "Mostaganem",
        "Msila",
        "Mascara",
        "Ouargla",
        "Oran",
        "El Bayadh",
        "Illizi",
        "Bordj Bou Arreridj",
        "Boumerdes",
        "El Tarf",
        "Tindouf",
        "Tissemsilt",
        "El Oued",
        "Khenchela",
        "Souk Ahras",
        "Tipaza",
        "Mila",
        "Aïn Defla",
        "Naama",
        "Aïn Temouchent",
        "Ghardaia",
        "Relizane",
        "Timimoun",
        "Bordj Badji Mokhtar",
        "Ouled Djellal",
        "Béni Abbès",
        "In Salah",
        "In Guezzam",
        "Touggourt",
        "Djanet",
        "El MGhaier",
        "El Meniaa",
      ],
    },
    status: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Alert", AlertSchema);
